m: fabs    FABS ;
m: flog2   FLOG2 ;
m: fcos    FCOS ;
m: fdup    FDUP ;
m: fswap   FSWAP ;
m: ds>f    DS>F ;
m: flog    FLOG ;
m: f1+     F1+ ;
m: f1-     1e F- ;
m: facos   FACOS ;
m: fln     FLN ;
m: fmin    FMIN ;
m: fnegate FNEGATE ;
m: fdepth  FDEPTH ;
m: f**2    F**2 ;
m: fsqrt   FSQRT ;
m: fasin   FASIN ;
m: fsin    FSIN ;
m: fatan   FATAN ;
m: fdrop   FDROP ;
m: f0<>    F0= INVERT ;
m: d>f     D>F ;
m: fmax    FMAX ;
m: fpi     FPI ;
m: f>ds    F>DS ;
m: ftan    FTAN ;
m: exp     EXP ;
m: f0=     F0= ;
m: f@      F@ ;
m: f!      F! ;
m: f+      F+ ;
m: f-      F- ;
m: f*      F* ;
m: f/      F/ ;
m: f=      F= ;
m: f<>     F= INVERT ;
m: f<      F< ;
m: f>      F< F= OR 0= ;
m: f~      F~ ;
m: f**     F** ;
m: f.      F. ;
: fprim ;
