: fabs    FABS ;
: flog2   FLOG2 ;
: fcos    FCOS ;
: fdup    FDUP ;
: fswap   FSWAP ;
: ds>f    DS>F ;
: flog    FLOG ;
: f1+     F1+ ;
: f1-     1e F- ;
: facos   FACOS ;
: fln     FLN ;
: fmin    FMIN ;
: fnegate FNEGATE ;
: fdepth  FDEPTH ;
: f**2    F**2 ;
: fsqrt   FSQRT ;
: fasin   FASIN ;
: fsin    FSIN ;
: fatan   FATAN ;
: fdrop   FDROP ;
: f0<>    F0= INVERT ;
: d>f     D>F ;
: fmax    FMAX ;
: fpi     FPI ;
: f>ds    F>DS ;
: ftan    FTAN ;
: exp     EXP ;
: f0=     F0= ;
: f@      F@ ;
: f!      F! ;
: f+      F+ ;
: f-      F- ;
: f*      F* ;
: f/      F/ ;
: f=      F= ;
: f<>     F= INVERT ;
: f<      F< ;
: f>      F< F= OR 0= ;
: f~      F~ ;
: f**     F** ;
: f.      F. ;
: fprim ;
