\ stenoforth32
\ перевод часто используемых имен слов в нижний регистр
SYNONYM exit         EXIT
SYNONYM c@           C@
SYNONYM w@           W@
SYNONYM c!           C!
SYNONYM w!           W!
SYNONYM c,           C,
SYNONYM w,           W,

SYNONYM dup          DUP
SYNONYM 2dup         2DUP
SYNONYM drop         DROP
SYNONYM 2drop        2DROP
SYNONYM swap         SWAP
SYNONYM 2swap        2SWAP
SYNONYM over         OVER
SYNONYM 2over        2OVER
SYNONYM nip          NIP
SYNONYM tuck         TUCK
SYNONYM rot          ROT
SYNONYM -rot         -ROT

SYNONYM sp@          SP@
SYNONYM sp!          SP!
SYNONYM depth        DEPTH
SYNONYM >r           >R
SYNONYM 2>r          2>R
SYNONYM r>           R>
SYNONYM 2r>          2R>
SYNONYM r@           R@
SYNONYM 2r@          2R@
SYNONYM rp@          RP@
SYNONYM rp!          RP!
SYNONYM rallot       RALLOT

SYNONYM .bl          .BL
SYNONYM bl           BL
SYNONYM space        SPACE
SYNONYM spaces       SPACES
SYNONYM d.           D.
SYNONYM cr           CR
SYNONYM hex          HEX
SYNONYM decimal      DECIMAL
SYNONYM type         TYPE
SYNONYM or           OR
SYNONYM xor          XOR
SYNONYM and          AND
SYNONYM invert       INVERT
SYNONYM lshift       LSHIFT
SYNONYM rshift       RSHIFT
SYNONYM dump         DUMP

SYNONYM true         TRUE
SYNONYM false        FALSE
SYNONYM if           IF
SYNONYM else         ELSE
SYNONYM then         THEN
SYNONYM case         CASE
SYNONYM of           OF
SYNONYM endof        ENDOF
SYNONYM endcase      ENDCASE

SYNONYM begin        BEGIN
SYNONYM again        AGAIN
SYNONYM until        UNTIL
SYNONYM while        WHILE
SYNONYM repeat       REPEAT

SYNONYM do           DO
SYNONYM ?do          ?DO
SYNONYM ado          aDO
SYNONYM i+           I+
SYNONYM i            I
SYNONYM j            J
SYNONYM leave        LEAVE
SYNONYM unloop       UNLOOP
SYNONYM loop         LOOP
SYNONYM +loop        +LOOP

SYNONYM create       CREATE
SYNONYM does>        DOES>
SYNONYM aligned      ALIGNED
SYNONYM align        ALIGN
SYNONYM align-nop    ALIGN-NOP

SYNONYM dp           DP
SYNONYM here         HERE
SYNONYM allot        ALLOT
SYNONYM cell         CELL
SYNONYM cells        CELLS

SYNONYM constant     CONSTANT
SYNONYM variable     VARIABLE
SYNONYM value        VALUE
SYNONYM 2variable    2VARIABLE
SYNONYM 2value       2VALUE
SYNONYM vect         VECT
SYNONYM ->vect       ->VECT
SYNONYM user         USER
SYNONYM user-value   USER-VALUE
SYNONYM user-create  USER-CREATE
SYNONYM allocate     ALLOCATE
SYNONYM resize       RESIZE
SYNONYM free         FREE
SYNONYM throw        THROW
SYNONYM recurse      RECURSE
SYNONYM latest       LATEST
SYNONYM last         LAST

SYNONYM lit,         LIT,
SYNONYM slit,        SLIT,
SYNONYM rlit,        RLIT,
SYNONYM dlit,        DLIT,
SYNONYM number?      NUMBER?
SYNONYM :noname      :NONAME
SYNONYM erase        ERASE
SYNONYM fill         FILL
SYNONYM compare      COMPARE
SYNONYM search       SEARCH
SYNONYM move         MOVE
SYNONYM emit         EMIT
SYNONYM spmove       SPMOVE
SYNONYM spdrop       SPDROP
SYNONYM sp>mem       SP>MEM
SYNONYM key          KEY
SYNONYM within       WITHIN
SYNONYM min          MIN
SYNONYM max          MAX
SYNONYM abs          ABS
SYNONYM negate       NEGATE
SYNONYM mod          MOD
SYNONYM /mod         /MOD
SYNONYM evaluate     EVALUATE
SYNONYM postpone     POSTPONE
SYNONYM execute      EXECUTE
SYNONYM immediate    IMMEDIATE
SYNONYM base         BASE
SYNONYM state        STATE

SYNONYM s"           S"
SYNONYM abort"       ABORT"
SYNONYM nextword     NextWord
SYNONYM wordbyaddr   WordByAddr
SYNONYM parse-name   PARSE-NAME
SYNONYM parse        PARSE

SYNONYM vocabulary   VOCABULARY
SYNONYM order        ORDER
SYNONYM only         ONLY
SYNONYM also         ALSO
SYNONYM definitions  DEFINITIONS
SYNONYM previous     PREVIOUS
SYNONYM context      CONTEXT
SYNONYM current      CURRENT
SYNONYM id.          ID.
SYNONYM name>        NAME>
SYNONYM name>f       NAME>F
SYNONYM name>c       NAME>C
SYNONYM to           TO
SYNONYM seet         SEET
SYNONYM set-opt      SET-OPT
SYNONYM dis-opt      DIS-OPT
